version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - ./data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'" ]
      interval: 20s
      timeout: 3s
      retries: 10
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "gws-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "s@cr3t"
    ports:
      - "5672:5672"
      - "15672:15672"

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE=en
    depends_on:
      elasticsearch:
        condition: service_healthy

  email-service:
    build: .
    container_name: email-service
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    env_file:
      - .env
    environment:
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
      - SPRING_RABBITMQ_HOST=rabbitmq